### ISSUE TITLE
引数がない/空文字列の場合の例外処理

### ISSUE THREAD

**Issue by TwoSquirrels** [laddge/termux-send-line#2]
引数なしで実行すると、何もエラーメッセージが出ないまま固まってしまいます。
処理中かと勘違いしてしまいます。

また空文字列だった場合、LINEアプリ側からURLの間違いを指摘されてしまいます。

これらは事前に引数をチェックしエラーメッセージを返すべきだと思いますので、
修正よろしくお願いします。

**Comment by laddge** [comment]
空文字の判定を追加しました。
あと、何も引数がないときは標準入力から受け取る仕様です。
